language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  - pip

before_install:
  - travis_retry sudo apt-get install -y inkscape

install:
  - travis_retry pip install -q cython numpy
  - pip install -e .

script:
  # test installation
  - python setup.py install
  # install packages for docs and make docs
  - travis_retry pip install -q ipython Sphinx sphinx-gallery numpydoc
  - cd docs && make html && cd ..
  # Tell GitHub not to use jekyll to compile the docs
  - touch docs/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
    # push only once
    python: "3.7"
  local_dir: docs/_build/html/
